Controllers/DiarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReffugeMVC.Models;

namespace ReffugeMVC.Controllers
{
    public class DiarioController : Controller
    {
        private readonly Contexto _context;

        public DiarioController(Contexto context)
        {
            _context = context;
        }

        // GET: Diario
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Diario.Include(d => d.Cliente);
            return View(await contexto.ToListAsync());
        }

        // GET: Diario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Diario == null)
            {
                return NotFound();
            }

            var diario = await _context.Diario
                .Include(d => d.Cliente)
                .FirstOrDefaultAsync(m => m.DiarioId == id);
            if (diario == null)
            {
                return NotFound();
            }

            return View(diario);
        }

        // GET: Diario/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "ClienteId", "NomeCliente");
            return View();
        }

        // POST: Diario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DiarioId,DataHorario,ConteudoDiario,ClienteId")] Diario diario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(diario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "ClienteId", "NomeCliente", diario.ClienteId);
            return View(diario);
        }

        // GET: Diario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Diario == null)
            {
                return NotFound();
            }

            var diario = await _context.Diario.FindAsync(id);
            if (diario == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "ClienteId", "NomeCliente", diario.ClienteId);
            return View(diario);
        }

        // POST: Diario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DiarioId,DataHorario,ConteudoDiario,ClienteId")] Diario diario)
        {
            if (id != diario.DiarioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(diario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiarioExists(diario.DiarioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Cliente, "ClienteId", "NomeCliente", diario.ClienteId);
            return View(diario);
        }

        // GET: Diario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Diario == null)
            {
                return NotFound();
            }

            var diario = await _context.Diario
                .Include(d => d.Cliente)
                .FirstOrDefaultAsync(m => m.DiarioId == id);
            if (diario == null)
            {
                return NotFound();
            }

            return View(diario);
        }

        // POST: Diario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Diario == null)
            {
                return Problem("Entity set 'Contexto.Diario'  is null.");
            }
            var diario = await _context.Diario.FindAsync(id);
            if (diario != null)
            {
                _context.Diario.Remove(diario);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DiarioExists(int id)
        {
          return (_context.Diario?.Any(e => e.DiarioId == id)).GetValueOrDefault();
        }
    }
}

Controllers/PlanosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReffugeMVC.Models;

namespace ReffugeMVC.Controllers
{
    public class PlanosController : Controller
    {
        private readonly Contexto _context;

        public PlanosController(Contexto context)
        {
            _context = context;
        }

        // GET: Planos
        public async Task<IActionResult> Index()
        {
              return _context.Planos != null ? 
                          View(await _context.Planos.ToListAsync()) :
                          Problem("Entity set 'Contexto.Planos'  is null.");
        }

        // GET: Planos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Planos == null)
            {
                return NotFound();
            }

            var planos = await _context.Planos
                .FirstOrDefaultAsync(m => m.PlanosId == id);
            if (planos == null)
            {
                return NotFound();
            }

            return View(planos);
        }

        // GET: Planos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Planos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlanosId,NomePlanos,PrecoPlanos,DescricaoPlanos,DuracaoPlanos")] Planos planos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(planos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(planos);
        }

        // GET: Planos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Planos == null)
            {
                return NotFound();
            }

            var planos = await _context.Planos.FindAsync(id);
            if (planos == null)
            {
                return NotFound();
            }
            return View(planos);
        }

        // POST: Planos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlanosId,NomePlanos,PrecoPlanos,DescricaoPlanos,DuracaoPlanos")] Planos planos)
        {
            if (id != planos.PlanosId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(planos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlanosExists(planos.PlanosId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(planos);
        }

        // GET: Planos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Planos == null)
            {
                return NotFound();
            }

            var planos = await _context.Planos
                .FirstOrDefaultAsync(m => m.PlanosId == id);
            if (planos == null)
            {
                return NotFound();
            }

            return View(planos);
        }

        // POST: Planos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Planos == null)
            {
                return Problem("Entity set 'Contexto.Planos'  is null.");
            }
            var planos = await _context.Planos.FindAsync(id);
            if (planos != null)
            {
                _context.Planos.Remove(planos);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlanosExists(int id)
        {
          return (_context.Planos?.Any(e => e.PlanosId == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReffugeMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ReffugeMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="menu navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="img-logo">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="logo" src="/img/loguinho-reffuge.png" /></a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planos" asp-action="Index">Planos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profissional" asp-action="Index">Profissional</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoEspecializacao" asp-action="Index">Especialização</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agendamento" asp-action="Index">Agendamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TermometroEmocional" asp-action="Index">Termometro Emocional</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoEmocao" asp-action="Index">Emoção</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conteudo" asp-action="Index">Conteúdo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoConteudo" asp-action="Index">Tipo Conteúdo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TermometroNoturno" asp-action="Index">Termometro Noturno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DuracaoSono" asp-action="Index">Duração Sono</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoSentimentoSono" asp-action="Index">Sentimento do Sono</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exercicios" asp-action="Index">Exercícios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoExercicios" asp-action="Index">Tipo Exercícios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Diario" asp-action="Index">Diário</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="rodape">
            &copy; 2024 - Reffuge - <a asp-area="" class="btn-danger2" asp-controller="Home" asp-action="Privacy">Política de Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>